### ISSUE TITLE
[Bug]: Mixin causing incompatibility with More Villagers mod

### ISSUE THREAD

**Issue by samedifferent** [YUNG-GANG/YUNGs-Better-Witch-Huts#2]
Minecraft: 1.18.2
Forge: 40.1.0
Better Witch Huts: 1.0
Yung's API: 2.0.8

The Florist villager profession from [More Villagers](https://www.curseforge.com/minecraft/mc-mods/more-villagers) sells a map that points to the vanilla swamp hut structure. Your mixin that disables the vanilla huts is causing a crash when the villager attempts to generate this trade. I see this can be disabled in the config, but I think a mixin like this is pretty intrusive, considering vanilla villagers use the same map trade listing and would crash if they happened to sell a swamp hut map. Since structure maps are data driven now, I suggest adding your current custom swamp huts, and any future huts you may create, to this tag: https://github.com/samedifferent/morevillagers/blob/1.18.2-crossplatform/common/src/main/resources/data/morevillagers/tags/worldgen/configured_structure_feature/on_swamp_hut_explorer_maps.json

**Comment by yungnickyoung** [comment]
@samedifferent Opened #3 to address this, please check that it satisfies the requirements!

**Comment by yungnickyoung** [comment]
Update: tested myself and seems to work properly. Went ahead and upload to Curseforge for both Forge and Fabric, v1.0.1. Let me know if it works for you and I'll close the issue.

Also, if you have any recommendations for better ways to disable vanilla structures, let me know!

**Comment by yungnickyoung** [comment]
Another update - I've gone ahead and made a similar addition to Better Mineshafts, available in v2.2. Should help fix any potential issues with the Miner villager.

**Comment by samedifferent** [comment]
Just tested and it works for me, thanks!
